### ISSUE TITLE
Implement a "clean" task

### ISSUE THREAD

**Issue by cjstehno** [jbake-org/jbake-gradle-plugin#11]
It would be nice to have a `clean` task available to wipe out the contents of the `build/jbake` directory.

**Comment by ronsmits** [comment]
Tbh a clean task could be as simple as
````
task clean(type: Delete) {
   delete 'builld/jbake'
}
````

**Comment by cjstehno** [comment]
True. That is what I ended up doing locally - what I really want is the stuff in the #5 pull request. I will go ahead and close this in hopes that request will be merged at some point.

**Comment by mperry** [comment]
That PR I wrote was opened a year ago now.  I don't know if it is relevant anymore.  @melix can you remember if there was a problem with this?  Should we be both be reviewing the changes to see what should be happening here?

**Comment by ItGumby** [comment]
doesn't
```gradle
apply plugin: 'base'
```
single-handedly provide the 'clean' task?

**Comment by ancho** [comment]
Yes. The plugin actually does apply the base plugin see discussion in #19
