### ISSUE TITLE
Link to an example

### ISSUE THREAD

**Issue by nedtwigg** [jbake-org/jbake-gradle-plugin#13]
If the top of the README.MD linked to some public repos that were using this plugin, that would make it easier to get started with.  Looks promising :)

**Comment by msgilligan** [comment]
Some of the sites on http://jbake.org/community/sites.html are using the plugin. For example https://github.com/melix/blog. Another one that is not listed on the JBake sites page is: https://github.com/danhyun/blog

**Comment by nedtwigg** [comment]
Thanks!  Very helpful.

At least for me, I discovered the plugin from this angle - "what gradle
plugin can I use for static site generation" rather than "how can I use
JBake with gradle" - I hadn't heard of JBake before.  So if the README has
stuff to point people like me in the right direction, then it might help
adoption.

Ned Twigg
Lead Software Architect, DiffPlug LLC
949-264-3433
340 S Lemon Ave #3433, Walnut, CA 91789

**Comment by msgilligan** [comment]
... And as of today, you can add mine to the list: http://msgilligan.github.io

**Comment by jonbullock** [comment]
Thanks for the suggestion and the list of sites. I've added details to the README.adoc here: ef7ca3faaa03ac40fd06c9abdf05dca603fd23d9
