### ISSUE TITLE
Add explicit support for JBake 2.4.0

### ISSUE THREAD

**Issue by msgilligan** [jbake-org/jbake-gradle-plugin#15]
It would be nice to see the README and examples use JBake 2.4.0.

(It seems to work for me, although I'm seeing Issue #14 with both 2.3.2 and 2.4.0.)

**Comment by antonmry** [comment]
@msgilligan, I've created a PR for jbake 2.40 #18 including the README, let me know if this PR closes this issue and your problem with #14

**Comment by aalmiray** [comment]
Fixed.
