### ISSUE TITLE
Authoritative fork?

### ISSUE THREAD

**Issue by kastork** [jbake-org/jbake-gradle-plugin#17]
I'm working on some changes to this plugin and I'm wondering....
1. Is the project still a going concern or should I consider just starting my own?
2. Which fork is authoritative?  This one seems like it should be since it is associated with jbake itself, but there are a few very old PR's so it is hard to tell.  The one at https://github.com/mperry/jbake-gradle-plugin seems most active.

**Comment by mperry** [comment]
I haven't touched my fork in a long time.  Best to hit up @melix to get this this repo up to date.  I'm not sure if there are other people with admin permissions, but this is the official one so we should continue with it.

**Comment by jonbullock** [comment]
I've not spoken to @melix about this plugin and maintenance going forward so I don't know what his views are, but if anyone else is interested in maintaining this plugin I'd be happy to grant them access? I would prefer this to stay as the authoritative repo for this plugin.

I just don't have the time at the moment to look at this as well as JBake.

**Comment by aalmiray** [comment]
I would be interested in keeping the project up to date. :smile:

**Comment by ancho** [comment]
:+1:

**Comment by mperry** [comment]
Who are the current administrators of the project?  I am unsure of how to check.

@aalmiray is a respected member of the Groovy community.  @jonbullock Can you add @aalmiray and myself, @mperry, as administrators of this project?

**Comment by jonbullock** [comment]
I'll do it now, thanks for stepping forward @aalmiray and @mperry :smile:

**Comment by jonbullock** [comment]
You should both have invites to the team that has write permission to this repo.

**Comment by aalmiray** [comment]
thanks a bunch @jonbullock :smile:

**Comment by antonmry** [comment]
Happy to know there new maintainers, thanks @aalmiray and @mperry ! If I can help with something, just let me know :+1:

**Comment by jonbullock** [comment]
@aalmiray @mperry do you have any issue if I grant @ancho access to this repo as well?

**Comment by codestoe** [comment]
Hi there,
is there any need, why this issue is still open?
