### ISSUE TITLE
release 0.3.0

### ISSUE THREAD

**Issue by ancho** [jbake-org/jbake-gradle-plugin#21]
I wonder if it's possible to release version 0.3.0 of the plugin?

0.2.1 was never released officially. There are a view features worth to release.

Currently it's published in @melix 's [gradle-repository](https://bintray.com/melix/gradle-plugins/jbake-gradle-plugin) at bintray and linked to jcenter.

Maybe it's time to create a jbake organization at bintray and move it there, if it's possible.

**Comment by rahulsom** [comment]
```groovy
buildscript {
  repositories {
    jcenter()
    maven { url "https://jitpack.io" }
  }
  dependencies {
    classpath 'com.github.jbake-org:jbake-gradle-plugin:1c20c305cb'
  }
}

apply plugin: 'me.champeau.jbake'
```

This might help you.

**Comment by ancho** [comment]
Yeah....actually no....but thanks for another solution to publish individual versions of libraries.
I did that with 0.2.1 at bintray. And a few people are using it already.
It's more about a public release to an official repository from people or organizations they trust.

**Comment by jonbullock** [comment]
I'm pretty sure I've registered the project at Bintray ages ago... let me
double check and confirm either way.

**Comment by jonbullock** [comment]
Yeah there is a JBake org on Bintray, I'll add you now.

**Comment by mariogarcia** [comment]
Any updates on this ? 

In the meantime I found this [blog entry](https://www.calmdevelopment.de/blog/2016/09/jbake-asciidoctor-diagram.html) and I'm using this guy repo and it works nicely. It's awesome to be able to use diagrams with Jbake :)

**Comment by rodm** [comment]
I see Bintray mentioned a few times above, what about updaing the [Gradle plugin repository](https://plugins.gradle.org/), the version there was publish 2.5 years ago. Also are there any plans to update the plugin id, to something like 'org.jbake'?

**Comment by ancho** [comment]
+1 for changing the plugin id.
I would also suggest to change the group as well and release a 1.0.0 version on jbake's bintray organization to make the transition to the organization clear.
Otherwise we might get problems publishing the binary on maven central, I guess.
I don't know if there are any implications regarding a sync to maven central if we would publish the binary to the jbake organisation but keep the group name.

@aalmiray what do you think? Do you have any experience with a transition to another group?

**Comment by aalmiray** [comment]
@ancho. I do. Yet the move to a different package/organization has to have the blessing/authorization from @melix, the original author of the plugin, IMHO.

**Comment by jonbullock** [comment]
I asked @melix if he'd be OK with newer versions being published under the org.jbake group/org and he said he has no problem with this. I've also asked if he can comment here to make it official.

**Comment by melix** [comment]
Yes, I have absolutely no problem with moving the plugin.

**Comment by aalmiray** [comment]
Plugin id proposal: 'org.jbake.site`.
Rationale: the current behavior of the plugin is to bootstrap and back a "site" project. We could later refine the plugin to provide even basic `jbake` features (thus an `org.jbake.base` or `org.jbake.bake-base` plugin may appear).

**Comment by rodm** [comment]
@aalmiray  Good to see these changes go in. However I noticed the version was bumped to 1.0.0-SNAPSHOT and this issue was about 0.3, so what's the plan for the next release?

**Comment by aalmiray** [comment]
Release as soon as possible once @jonbullock and @ancho review the changes. I think we're good to go for a release as is.

**Comment by jonbullock** [comment]
The plugin id proposal sounds good to me, I'm no expert on Gradle plugin development but everything looks good to me 👍

**Comment by ancho** [comment]
@aalmiray I'm fine with the plugin id. Thank you. Left a comment on the version changes.

**Comment by aalmiray** [comment]
release 1.0.0 has been posted to Bintray and the Gradle plugin portal

**Comment by mperry** [comment]
:+1:  Thanks @aalmiray
