### ISSUE TITLE
Add support for asciidoctor diagram

### ISSUE THREAD

**Issue by rahulsom** [jbake-org/jbake-gradle-plugin#24]
I would like to insert a diagram into an asciidoctor post using asciidoctor-diagram.

This forum discussion might be relevant - https://groups.google.com/forum/#!topic/jbake-user/qjS_ojssKF0

**Comment by ancho** [comment]
As jbake released version 2.5.0 it is now possible to use asciidoctor-diagram as demonstrated in my blog post. Maybe you can try my example and give me some feedback if it works for you.
Or do you have something else on your mind?

**Comment by msgilligan** [comment]
I have it working in 2.6.0. Maybe we should just document how to do it?

**Comment by aalmiray** [comment]
Thus is not an issue on the plugin, rather on how jbake is configured.
