### ISSUE TITLE
www.jbake.org links are broken (it's just https://jbake.org)

### ISSUE THREAD

**Issue by brianoliver** [jbake-org/jbake-gradle-plugin#40]
In a few places in the readme there are links to https://www.jbake.org/.   These fail with a 404 error.  Instead they should be https://jbake.org

**Comment by jonbullock** [comment]
Thanks for raising this, we've recently switched the hosting over for the site and started using Cloudflare so I'll look into this now.

**Comment by jonbullock** [comment]
Changed to Cloudflare config to fix this, if you're still seeing 404 errors please let me know by re-opening this issue.

**Comment by brianoliver** [comment]
Looks good now!  Thanks!
