### ISSUE TITLE
Concurrent bake task cause Gradle to crash

### ISSUE THREAD

**Issue by lacasseio** [jbake-org/jbake-gradle-plugin#53]
If multiple bake tasks are run in parallel, the bake tasks will fail, see https://scans.gradle.com/s/vcubcmopsw2vg

I suspect [this static variable](https://github.com/jbake-org/jbake-gradle-plugin/blob/master/src/main/groovy/org/jbake/gradle/JBakeTask.groovy#L42) is the cause.

I suggest using the worker API with at least the class loader isolation and load the jbake dependency in the worker classloader. If you agree with this assessment, I can do a quick PR to fix this.

The current workaround is to ensure each task runs one after the other, see the somewhat general code to fix the issue:

```
GroovyCollections.transpose(subprojects.drop(1).asList(), subprojects as List).each {
	def downstream = it[0]
	def upstream = it[1]
	upstream.afterEvaluate { proj ->
		proj.evaluationDependsOn(downstream.path)
		proj.tasks.named('bake') {
			it.mustRunAfter(downstream.tasks.named('bake'))
		}
	}
}
```

**Comment by aalmiray** [comment]
What would be the minimum Gradle version required for this patch to work?

**Comment by lacasseio** [comment]
According to the documentation, the [worker API was introduced in 3.5](https://docs.gradle.org/current/javadoc/org/gradle/workers/WorkerExecutor.html).

**Comment by lacasseio** [comment]
You could still support older versions by using the previous logic. We would have to detect Gradle during the task execution.

**Comment by aalmiray** [comment]
I believe the minimum required Gradle version for this plugin is `5.1`, thus a patch with workers should be doable.
