### ISSUE TITLE
Plugin leaks a lot of memory

### ISSUE THREAD

**Issue by lacasseio** [jbake-org/jbake-gradle-plugin#56]
It may be related to https://github.com/jbake-org/jbake-gradle-plugin/issues/31.

I have four projects executing JBake task and they can barely execute without an out of memory exception. I did some profiling and I can confirm there are memory leaks. [I suspect the following code](https://github.com/jbake-org/jbake-gradle-plugin/blob/master/src/main/groovy/org/jbake/gradle/JBakeTask.groovy#L70-L100). What's the reason for dynamically loading classes?

I believe moving the worker API would mostly solve the issue.

**Comment by aalmiray** [comment]
I believe the code for dynamically loading classes was added many years a go by @melix, following a similar approach applied to the JMH plugin (back in the late Gradle 2.x, early 3.x time)

**Comment by melix** [comment]
I don't recall doing that. It's indeed years old, but it seems it was introduced in this commit: https://github.com/jbake-org/jbake-gradle-plugin/commit/7b7cf1176462a4d868b9423d7e22f8f0e484ba67

That said the approach that @lacasseio suggests is much better and the way to go.
