### ISSUE TITLE
bakePreview does not shut down in a proper way

### ISSUE THREAD

**Issue by rdmueller** [jbake-org/jbake-gradle-plugin#58]
maybe I do something wrong...

I often run `./gradlew bakePreview` on windows in the build in terminal of IntelliJ.
Whenever I stop the server through `ctrl+c`, the terminal return control to me, but a java process is still running which blocks the https port.

I always have to kill this process before I can restart `bakePreviw`.

any ideas?

**Comment by ancho** [comment]
i have the same problem on linux as well. try running it with `./gradlew bakePreview --no-daemon`
seems like running in daemon mode does not delegate the signal to stop the spawned process or something like that.

**Comment by rdmueller** [comment]
thanx - that is quite helpful information!
